list_names = [
"Ashish Agrawal",
"Pallavi",
"Deepak Kumar",
"Deepak Kumar",
"Rohan Salunkhe",
"Pallavi",
"Vatsal Sharma",
"Krishna Garg",
"Navyath Sabbani",
"Suryasen",
"Duy Tri Nguyen",
"Abdul Quadir",
"Md Mahfuz ",
"Pallavi",
"Harsh Chaudhary ",
"HARIHARAN P G",
"Chetan Danam",
"Ghanshyam Singh ",
"VANSHAM SAHULKUMAR SHAH",
"Rajan Patel ",
"DARAKHSHAN NAHEED ",
"Kashish Khare",
"DHANUSHYA S",
"Duy Tri Nguyen",
"Unnati Kishor Girase",
"Prince Vagadiya ",
"Prince Vagadiya",
"VANSH TOMAR",
"Divyanjali Sharma ",
"Kamran Faraz Khan",
"Sunil Kumar Gurjar",
"Harsh Chaudhary ",
"SAI ASISH GOUDO",
"Rohan Salunkhe",
"ARUN S MALI",
"ARUN S MALI",
"Sharmeen Javed Shaikh",
"Navyath Sabbani",
"DARAKHSHAN NAHEED ",
"Bhushan Bhaskar Sagar",
"Shenthuri Maran",
"Sanskruti Anant Misal",
"Rajan Patel",
"ARUN S MALI",
"Harsh Chaudhary",
"Siddhi Rajendra Ghode",
"Kamran Faraz Khan",
"Pratham Akkewar",
"Ghanshyam Singh ",
"Kiran Kumar",
"Saurav Narendra Chafle ",
"Gaurav Chafle ",
]

list_emails=[
"ashish027120@gmail.com",
"pallaviiti2018@gmail.com",
"kumardeepakshakya06@outlook.com",
"kumardeepakshakya06@outlook.com",
"rohansalunkhe858@gmail.com",
"pallaviiti2018@gmail.com",
"vatsalsh3002@gmail.com",
"gargkrishna730@gmail.com",
"navyathsabbani@gmail.com",
"myselfsuryasen@gmail.com",
"duytringuyenshsg20210707@outlook.com",
"aq0132374@gmail.com",
"mdmahfuz7050@gmail.com",
"pallaviiti2018@gmail.com",
"harshchaudhary2307@gmail.com",
"hariharangpl@outlook.com",
"danamchetan007@gmail.com ",
"ghanshyam2005singh@gmail.com",
"vansham2608@gmail.com",
"patelrajan2132003@gmail.com",
"khandolly378@gmail.com",
"Kashish.khare547@oulook.com",
"dhanushyas1806@gmail.com",
"duytringuyenshsg20210707@outlook.com",
"Kishorgirase52@gmail.com",
"princevagadiya2005@gmail.com",
"princevagadiya2005@gmail.com",
"VANSHTOMAR2504@OUTLOOK.COM",
"divyanjalisharma30@gmail.com",
"kamranfaraz41@gmail.com",
"gurjarsiddharth8721@outlook.com",
"harshchaudhary2307@gmail.com",
"saiasishgoudo027@gmail.com",
"rohansalunkhe858@gmail.com",
"arunsmali2002@gmail.com",
"arunsmali2001@outlook.com",
"shaikhsharmeen4849@gmail.com",
"navyathsabbani@gmail.com",
"khandolly378@gmail.com",
"aeronautbhushan@gmail.com",
"Shenthurimaran@gmail.com",
"sanskrutimisal2602@gmail.com",
"patelrajan2132003@gmail.com",
"arunsmali2001@outlook.com",
"harshchaudhary2307@gmail.com",
"siddhighode05@gmail.com",
"kamranfaraz41@gmail.com",
"prathamakkewar7@gmail.com",
"ghanshyam2005singh@gmail.com",
"kk9840042@gmail.com",
"chaflesaurav@gmail.com",
"gauravchafle518@gmail.com ",
]





files = open("recervers.txt","w+")
# files.write(f"name,email,attachment,subject\n")
# "C:\Users\R. TARUN NAYAKA\Downloads\Power Platform Fundamentals\Abdul Nasir.pdf"
for i in range(len(list_names)):
    # attachment = f"C:\Users\R. TARUN NAYAKA\Downloads\Power Platform Fundamentals\{i}.pdf"
    # subject=""
    files.write(f"{list_names[i]},{list_emails[i]}\n")


